# Generated by Django 4.0 on 2021-12-16 06:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='djangoclasses',
            managers=[
                ('objecets', django.db.models.manager.Manager()),
            ],
        ),
    ]
