# Generated by Django 4.0 on 2021-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_djangoclasses_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='djangoclasses',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_number',
            field=models.IntegerField(choices=[('200', '200'), ('100', '100'), ('102', '102')]),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='instructor',
            field=models.CharField(choices=[('A.Jones', 'A.Jones'), ('K.Byrant', 'K.Bryant'), ('M.Hatter', 'M.Hatter')], max_length=30),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('Django 102', 'Django 102'), ('Django 101', 'Django 101'), ('Django 103', 'Django 103')], max_length=30),
        ),
    ]
