# Generated by Django 4.0 on 2021-12-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_alter_djangoclasses_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_number',
            field=models.IntegerField(choices=[('100', '100'), ('200', '200'), ('102', '102')]),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='instructor',
            field=models.CharField(choices=[('K.Bryant', 'K.Bryant'), ('M.Hatter', 'M.Hatter'), ('A.Jones', 'A.Jones')], max_length=30),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('Django 103', 'Django 103'), ('Django 101', 'Django 101'), ('Django 102', 'Django 102')], max_length=30),
        ),
    ]
