# Generated by Django 4.0 on 2021-12-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_alter_djangoclasses_course_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_number',
            field=models.IntegerField(choices=[('200', '200'), ('102', '102'), ('100', '100')]),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='instructor',
            field=models.CharField(choices=[('K.Bryant', 'K.Bryant'), ('A.Jones', 'A.Jones'), ('M.Hatter', 'M.Hatter')], max_length=30),
        ),
    ]
