# Generated by Django 4.0 on 2021-12-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0006_alter_djangoclasses_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='instructor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
